
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      server:
        git:
          uri: 
          basedir: /Users/*/Documents/IDEA/SpringCloud-Example/basedir
          username:
          password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: CONFIG-SERVER
management:
  endpoints:
    web:
      exposure:
        include: "*"